### ISSUE TITLE
map_123

### ISSUE THREAD

**Issue by LoveSimons** [ZZUTK/SRNTT#10]
Hello, thank you for the open source of the code, I am very interested in your research content, but I have a mistake in training, find the reason, is missing the map_123 file, I want to know how to get the "map_123" file, you Can you share the link to me?
look forward to your reply!

**Comment by nile649** [comment]
how many files are folder map_123, and what is total space consumption?

**Comment by ZZUTK** [comment]
Please run offline_patchMatch_textureSwap.py

**Comment by LoveSimons** [comment]
Thank you very much for your reply. I will further study your code and wish you a happy life




------------------ 原始邮件 ------------------
发件人: "Zhifei Zhang"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 中午1:29
收件人: "ZZUTK/SRNTT"<SRNTT@noreply.github.com>;
抄送: "guanlaifu"<351161991@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZZUTK/SRNTT] map_123 (#10)




Please run offline_patchMatch_textureSwap.py
