### ISSUE TITLE
You did'nt explained or mention anything about the following lines?

### ISSUE THREAD

**Issue by nile649** [ZZUTK/SRNTT#11]
````
back projection loss
```
`

could you please explain back projection loss?

**Comment by nile649** [comment]
Also, how are you exactly creating low res image from input?

**Comment by ZZUTK** [comment]
The back projection loss was tested in our implementation but it is not really used in the paper. The back projection loss aims to measure the pixel distance between LR input and bicubic downscaled SR output, ensuring that the output would not divert from the input after adding texture from the reference.

**Comment by nile649** [comment]
Thanks for an awesome idea.
