### ISSUE TITLE
How was upsacle.npz file created  before running offine_pathMatch_textureSwap.py

### ISSUE THREAD

**Issue by xd17** [ZZUTK/SRNTT#14]
In your codes, only after run offline_pathcMatch_textureSawp.py to create corresponding maps,  SRNTT net can be trained, I am confused with how upscale.npz file can be created before running offline_pathcMatch_textureSawp.py? could you explain for me, thanks

**Comment by ZZUTK** [comment]
The upscale.npz is the model for pre-upscale, which is actually a pre-trained SRGAN model.

**Comment by xd17** [comment]
thanks for your reply

**Comment by Lishiyuan0813** [comment]
Hi,I want to know which dataset does it use to train this pretrained model(upscale.npz)?Thank you!
