### ISSUE TITLE
about training epoch and loss

### ISSUE THREAD

**Issue by Lishiyuan0813** [ZZUTK/SRNTT#19]
Hi, How can I know the training is done?The losses especially l_dis seem always not to converge.
Thank you very much!

**Comment by Jam-G** [comment]
The model is training with a GAN, and
the `l_dis` is the loss for Discriminator.
If the  Generator is well trained ，` l_dis` should not converge expectedly.
The `l_dis` not to converge means the Discriminator can hardly distinguish a fake image（SR）from its ground truth（HR).
And it also means the Generator is trained successfully.

For model convergence，you should concern other losses， such as：
    - `total loss` for overall convergence
    - `l_adv` for adversary loss
    - `l_per` for perceptual loss
    - `l_tex` for texture loss
     ...

**Comment by Lishiyuan0813** [comment]
Great!Thank you  very much.
